<pre class='metadata'>
Title: WebGPU Explainer
Shortname: webgpu-explainer
Level: 1
Status: LS
Group: webgpu
URL: https://gpuweb.github.io/gpuweb/explainer/
!Participate: <a href="https://github.com/gpuweb/gpuweb/issues/new?labels=explainer">File an issue</a> (<a href="https://github.com/gpuweb/gpuweb/labels/explainer">open issues</a>)
!Translator: Lingyun, lingyun.zhao@orillusion.com
Editor: Kai Ninomiya, Google https://www.google.com, kainino@google.com
Editor: Corentin Wallez, Google https://www.google.com, cwallez@google.com
Editor: Dzmitry Malyshau, Mozilla https://www.mozilla.org, dmalyshau@mozilla.com
No Abstract: true
Markup Shorthands: markdown yes
Markup Shorthands: dfn yes
Markup Shorthands: idl yes
Markup Shorthands: css no
Assume Explicit For: yes
Boilerplate: repository-issue-tracking no
</pre>

Issue(tabatkins/bikeshed#2006): Set up cross-linking with the WebGPU and WGSL specifications.

Issue(gpuweb/gpuweb#1321): Complete the planned sections.


# Introduction # {#introduction}

WebGPU is a proposed Web API that enables web pages to use the system's [GPU (Graphics Processing Unit)](https://en.wikipedia.org/wiki/Graphics_processing_unit) to perform computations and draw complex images that can be presented inside the page.
This goal is similar to the [WebGL](https://www.khronos.org/webgl/) family of APIs, but WebGPU enables access to more advanced features of GPUs.
Whereas WebGL is mostly for drawing images but can be (with great effort) repurposed for other kinds of computations, WebGPU has first-class support for performing general computations on the GPU.

## Use Cases ## {#use-cases}

Example use cases for WebGPU that are not addressed by WebGL 2 are:

 - Drawing images with highly detailed scenes with many different objects (for example CAD models). WebGPU's draw commands are individually cheaper than WebGL's.
 - Executing advanced algorithms used to draw photorealistic scenes. Many modern rendering techniques and optimizations cannot be performed on WebGL 2 due to the lack of support for general computation.
 - Executing machine learning models efficiently on the GPU. General-purpose GPU (GPGPU) computations are possible in WebGL, but they are suboptimal and much more difficult.

Concrete examples are as follows:

 - Improving existing Javascript 3D libraries like Babylon.js and Three.js, using new rendering techniques (compute-based particles, more advanced post-processing, etc.) and offloading expensive computations currently done on the CPU (culling, skinned models) to the GPU.
 - Porting more recent game engines to the Web and enabling the engines to expose more advanced rendering functionality. For example Unity's WebGL export uses the lowest feature set of the engine, but WebGPU could use a higher feature set.
 - Porting a new class of applications to the Web: many productivity applications offload computations to the GPU and need WebGPU's support for general computation.
 - Improving existing web teleconferencing applications. For example Google Meet uses machine learning to separate the user from the background. Running the machine learning in WebGPU would make it faster and more power-efficient, allowing (1) these features to reach cheaper and more accessible user devices, and (2) more complex and powerful models.

## Goals ## {#goals}

Goals:

 - Support both realtime on-screen rendering and off-screen rendering.
 - Enable general-purpose computation to be performed efficiently on the GPU.
 - Support implementations targeting a variety of native GPU APIs: Microsoft's D3D12, Apple's Metal, and Khronos's Vulkan.
 - Provide a human-authorable language to specify computations to run on the GPU.
 - Be implementable in the multi-process architecture of a browser, maintaining the security of the Web.
 - Make applications work portably across different user systems and browsers as much as possible.
 - Interact with the rest of the Web platform in useful but carefully-scoped ways (essentially sharing images one way or another).
 - Provide a base on top of which modern GPU functionality can be exposed on the Web.
     WebGPU is structured similarly to all the current native GPU APIs, even if it doesn't provide all their functionality.
     There are plans to extend it later to have more modern functionality.
     See also: [[#why-not-webgl3]].

Non-goals:

 - Expose support for hardware that is not at all programmable, or less flexible, such as DSPs or specialized machine learning hardware.
 - Expose support for hardware that cannot do general-purpose computation (such as old phone GPUs or even old desktop GPUs).
 - Exhaustively expose all the functionality available on native GPU APIs (some functionality is only available on a single vendor's GPUs, or is too niche to be added to WebGPU).
 - Allow broadly mixing and matching WebGL and WebGPU code.
 - Integrate tightly with page rendering flows such as [CSS Houdini](https://developer.mozilla.org/en-US/docs/Web/Houdini).

## Why not "WebGL 3"? ## {#why-not-webgl3}

WebGL 1.0 and WebGL 2.0 are Javascript projections of the OpenGL ES 2.0 and OpenGL ES 3.0 APIs, respectively. WebGL's design dates back to the OpenGL 1.0 API released in 1992 (and further back to IRIS GL from the 1980s). This lineage has many advantages, including a large body of available knowledge and the relative ease of porting applications from OpenGL ES to WebGL.

However, it also means WebGL doesn't match the design of modern GPUs, causing CPU-performance and GPU-performance problems. It also makes implementing WebGL on top of modern native GPU APIs increasingly difficult. [WebGL 2.0 Compute](https://www.khronos.org/registry/webgl/specs/latest/2.0-compute/) attempted to add general-purpose computation to WebGL, but the impedance mismatch with the native APIs made the effort very hard. Contributors to WebGL 2.0 Compute decided to focus their efforts on WebGPU instead.

# More background # {#background}

## Sandboxed GPU Processes in Web Browsers ## {#gpu-process}

A major part of the design of WebGPU is that it must be implementable and efficient in browsers that use a GPU-process architecture.
GPU drivers need access to additional kernel syscalls than what's otherwise used for Web content, and many GPU drivers are prone to hangs or crashes.
To improve stability and sandboxing, browsers use a special process that contains the GPU driver and talks with the rest of the browser through asynchronous IPC.
GPU processes are (or will be) used in Chromium, Gecko, and WebKit.

GPU processes are less sandboxed than content processes, and they are typically shared between multiple origins.
Therefore, they must validate all messages, for example to prevent a compromised content process from being able to look at the GPU memory used by another content process.
Most of WebGPU's validation rules are necessary to ensure secure usage, so all the validation needs to happen in the GPU process.

Likewise, all GPU driver objects only exist in the GPU process, including large allocations (like buffers and textures) and complex objects (like pipelines).
In the content process, WebGPU types (`GPUBuffer`, `GPUTexture`, `GPURenderPipeline`, etc.) are mostly just "handles" that identify objects that live in the GPU process.
This means that the CPU and GPU memory used by WebGPU objects isn't necessarily known in the content process.
A `GPUBuffer` object can use maybe 150 bytes of CPU memory in the content process but hold on to a 1GB GPU memory allocation.

See also the description of [content and device timelines in the specification](https://gpuweb.github.io/gpuweb/#programming-model-timelines).

## Memory Visibility with GPUs and GPU Processes ## {#memory-visibility}

The two major types of GPUs are called "integrated GPUs" and "discrete GPUs".
Discrete GPUs are separate from the CPU; they are usually PCI-e cards that plug into the computer's motherboard.
Integrated GPUs are on the same chip as the CPU and don't have their own memory chips; instead, they use the same RAM as the CPU.

When using a discrete GPU, it's easy to see that most GPU memory allocations are not visible to the CPU because they are inside the GPU's RAM (or VRAM for video RAM).
For integrated GPUs, most memory allocations are in the same physical location, but are not visible to the GPU for various reasons (for example the CPU and GPU can have different caches for the same memory, so accesses aren't cache-coherent).
Instead, for the CPU to see the content of a GPU buffer, it must be "mapped", making it available in the virtual memory space of the application (think of mapping like in `mmap()`).
GPUBuffers must be specially allocated in order to be mappable - this can make them less efficient to access from the GPU (for example if they need to be allocated in RAM instead of VRAM).

All this discussion is centered around native GPU APIs, but in browsers, the GPU driver is loaded in the *GPU process*, so native GPU buffers can only be mapped in the GPU process's virtual memory.
In general, it is not possible to map the buffer directly inside the *content process* (though some systems can do this, providing an optional optimization).
To use this architecture, an extra "staging" allocation is needed in shared memory between the GPU process and the content process.

The table below recaps which type of memory is visible where:

<table class="data">
    <thead>
        <tr>
            <th>
            <th> Regular `ArrayBuffer`
            <th> Shared Memory
            <th> Mappable GPU buffer
            <th> Non-mappable GPU buffer (or texture)
        </tr>
    </thead>
    <tr>
        <td> CPU, in the content process
        <td> **Visible**
        <td> **Visible**
        <td> Invisible
        <td> Invisible
    <tr>
        <td> CPU, in the GPU process
        <td> Invisible
        <td> **Visible**
        <td> **Visible**
        <td> Invisible
    <tr>
        <td> GPU
        <td> Invisible
        <td> Invisible
        <td> **Visible**
        <td> **Visible**
</table>


# JavaScript API # {#api}

This section goes over important and unusual aspects of the WebGPU JavaScript API.
In general, each subsection can be considered its own "explanation unit", though some do require context from earlier subsections.


## Adapters and Devices ## {#adapters-and-devices}

A WebGPU "adapter" (`GPUAdapter`) is an object which identifies a particular WebGPU implementation on the system (e.g. a hardware-accelerated implementation on an integrated or discrete GPU, or a software implementation).
Two different `GPUAdapter` objects on the same page could refer to the same underlying implementation, or to two different underlying implementations (e.g. integrated and discrete GPUs).

The set of adapters visible to the page is determined by the user agent.

A WebGPU "device" (`GPUDevice`) represents a logical connection to a WebGPU adapter.
It is called a "device" because it abstracts away the underlying implementation (e.g. video card) and encapsulates a single connection: code that owns a device can act as if it is the only user of the adapter.

As part of this encapsulation, a device is the root owner of all WebGPU objects created from it (textures, etc.), which can be (internally) freed whenever the device is lost or destroyed.
Multiple components on a single web page can each have their own WebGPU device.

All WebGPU usage is done through a WebGPU device or objects created from it.
In this sense, it serves a subset of the purpose of `WebGLRenderingContext`;
however, unlike `WebGLRenderingContext`, it is not associated with a canvas object, and most commands are issued through "child" objects.

### Adapter Selection and Device Init ### {#initialization}
To get an adapter, an application calls `navigator.gpu.requestAdapter()`, optionally passing options that may influence the selection of the adapter, like `powerPreference` (`"low-power"` or `"high-performance"`) or
`forceSoftware` to force a software implementation.

`requestAdapter()` never rejects, but may resolve to null if an adapter couldn't be returned with the specified options.

The returned adapter exposes a `name` (implementation-defined), a boolean `isSoftware` so applications that have fallback paths (like WebGL or 2D canvas) can avoid using slow software implementations, and the [[#optional-capabilities]] on the adapter.

<pre highlight=js>
const adapter = await navigator.gpu.requestAdapter(options);
if (!adapter) return goToFallback();
</pre>

To get a device, an application calls `adapter.requestDevice()`, optionally passing a descriptor that enables additional optional capabilities - see [[#optional-capabilities]].

`requestDevice()` will reject (only) if the request is invalid, i.e. it exceeds the capabilities of the adapter.
If anything else goes wrong in the creation of the device, it will resolve to an already-lost `GPUDevice` - see [[#device-loss]].
(This simplifies the number of different cases the application has to handle, by avoiding extra possible return values like `null` or other exception types.)

<pre highlight=js>
const device = await adapter.requestDevice(descriptor);
device.lost.then(recoverFromDeviceLoss);
</pre>

An adapter may become unavailable, e.g. if it is unplugged from the system, disabled to save power, or marked "stale" (`[[current]]` becomes false).
From that point on, such an adapter can no longer vend valid devices, and always returns an already-lost `GPUDevice`.

### Optional Capabilities ### {#optional-capabilities}

Each adapter may have different optional capabilities, called "features" and "limits".
These are the maximum possible capabilities that can be requested when a device is created.

The set of optional capabilities exposed on each adapter is determined by the user agent.

A device is created with an exact set of capabilities, specified in the arguments to
`adapter.requestDevice()` (see above).

When any work is issued to a device, it is strictly validated against the capabilities of the device, not the capabilities of the adapter.
This simplifies the development of portable applications by avoiding implicit dependence on the capabilities of the development system.


## Object Validity and Destroyed-ness ## {#invalid-and-destroyed}

### WebGPU's Error Monad ### {#error-monad}

A.k.a. contagious internal nullability.
A.k.a. transparent [promise pipelining](http://erights.org/elib/distrib/pipeline.html).

WebGPU is a very chatty API, with some applications making tens of thousands of calls per frame to render complex scenes.
We've seen that the GPU processes needs to validate the commands to satisfy its security property.
To avoid the overhead of validating commands twice in both the GPU and the content process, WebGPU is designed so Javascript calls can be forwarded directly to the GPU process and validated there.
See the error section for more details on where the validation happens and how errors are reported.

At the same time, WebGPU objects that depend on one another can be created during a single frame.
For example a `GPUCommandBuffer` can be recorded with commands that use temporary `GPUBuffer`s created in the same frame.
In this example, because of WebGPU's performance constraints, it is not possible to send the message to create the `GPUBuffer` to the GPU process and synchronously wait for its processing before continuing Javascript execution.

Instead, in WebGPU, all objects (like `GPUBuffer`) are created immediately on the content timeline and returned to JavaScript.
The validation is almost all done asynchronously on the "device timeline".
In the good case, when no error occurs, everything looks to JS as if it is synchronous.
However, when an error occurs in a call, it becomes a no-op (aside from error reporting).
If the call returns an object (like `createBuffer`), the object is tagged as "invalid" on the GPU process side.

Since validation and allocation happen asynchronously, errors are reported asynchronously.
By itself, this can make some debugging challenging - see [[#errors-cases-debugging]].

All WebGPU calls validate that all their arguments are valid objects.
As a result, if a call takes a WebGPU object and returns a new object, the new object is also invalid (hence the term "contagious").

<figure>
    <figcaption>
        Timeline diagram of messaging between processes, showing how errors are propagated without synchronization.
    </figcaption>
    <object type="image/svg+xml" data="/images/error_monad_timeline_diagram.svg"></object>
</figure>

<div class=example>
    Using the API when only making valid calls looks like a synchronous API:

    <pre highlight="js">
        const srcBuffer = device.createBuffer({
            size: 4,
            usage: GPUBufferUsage.COPY_SRC
        });

        const dstBuffer = ...;

        const encoder = device.createCommandEncoder();
        encoder.copyBufferToBuffer(srcBuffer, 0, dstBuffer, 0, 4);

        const commands = encoder.finish();
        device.queue.submit([commands]);
    </pre>
</div>

<div class=example>
    Errors are contagious when objects are created:

    <pre highlight="js">
        // The size of the buffer is too big, this causes an OOM and srcBuffer is invalid.
        const srcBuffer = device.createBuffer({
            size: BIG_NUMBER,
            usage: GPUBufferUsage.COPY_SRC
        });

        const dstBuffer = ...;

        // The encoder starts as a valid object.
        const encoder = device.createCommandEncoder();
        // Special case: an invalid object is used when encoding commands, so the encoder
        // becomes invalid.
        encoder.copyBufferToBuffer(srcBuffer, 0, dstBuffer, 0, 4);

        // Since the encoder is invalid, encoder.finish() is invalid and returns an invalid object.
        const commands = encoder.finish();
        // The command references an invalid object so it becomes a no-op.
        device.queue.submit([commands]);
    </pre>
</div>

#### Mental Models #### {#error-monad-mental-model}

One way to interpret WebGPU's semantics is that every WebGPU object is actually a `Promise` internally and that all WebGPU methods are `async` and `await` each of the WebGPU objects it uses as arguments.
However, the execution of the async code is outsourced to the GPU process (where it is actually done synchronously).

Another way, closer to the actual implementation details, is to imagine that each `GPUFoo` JS object maps to a `gpu::InternalFoo` C++/Rust object on the GPU process that contains a `bool isValid`.
Then during the validation of each command on the GPU process, the `isValid` are checked, and a new invalid object is returned if validation fails.
On the content process side, the `GPUFoo` implementation doesn't know if the object is valid or not.

### Early Destruction of WebGPU Objects ### {#early-destroy}

Most of the memory usage of WebGPU objects is in the GPU process: it can be GPU memory for objects like GPUBuffer and GPUTexture, serialized commands in CPU memory for GPURenderBundles, or complex object graphs for the WGSL AST in `GPUShaderModule`.
The JavaScript garbage collector (GC) is in the renderer process and doesn't know about the memory usage in the GPU process.
Browsers have many heuristics to trigger GCs, but one common one is that it should be triggered on memory pressure scenarios.
However a single WebGPU object can hold onto megabytes or gigabytes of memory without the GC knowing and never trigger the memory pressure event.

It is important for WebGPU applications to be able to directly free the memory used by some WebGPU objects without waiting for the GC.
For example applications might create temporary textures and buffers each frame and without explicit `.destroy()` calls they could quickly run out of GPU memory.
That's why WebGPU has a `.destroy()` method on those object types that can hold on to arbitrary amount of memory.
It signals that the application doesn't need the content of the object anymore and that it can be freed as soon as possible.
Of course, using the object after the call to `.destroy()` becomes a validation error.

<div class=example>
    <pre highlight="js">
        const dstBuffer = device.createBuffer({
            size: 4
            usage: GPUBufferUsage.COPY_DST
        });

        // The buffer is not destroyed (and valid), success!
        device.queue.writeBuffer(dstBuffer, 0, myData);

        buffer.destroy();

        // The buffer is now destroyed, commands using that would use its
        // content produce validation errors.
        device.queue.writeBuffer(dstBuffer, 0, myData);
    </pre>
</div>

Note that while this looks somewhat similar to the behavior of an invalid buffer, it is different.
Unlike invalidness, destroyed-ness can change after creation, is not contagious, and is validated only when work is actually submitted (e.g. `queue.writeBuffer()` or `queue.submit()`), not when creating dependent objects (like command encoders, see above).

## Errors ## {#errors}

In a simple world, error handling in applications would be synchronous with JavaScript exceptions.
However, for a multi-process WebGPU implementation, this is very expensive.

See [[#invalid-and-destroyed]], which also explains how the *browser* handles errors.

### Problems and Solutions ### {#errors-solutions}

There are several cases developers and applications need error handling for:

- *Debugging*:
    Getting errors synchronously during development, to break in to the debugger.
- *Fatal Errors*:
    Handling device/adapter loss, by recovering WebGPU or falling back to non-WebGPU content.
- *Fallible Allocations*:
    Making fallible GPU memory resource allocations (detecting out-of-memory conditions).
- *Fallible Validation*:
    Checking whether a WebGPU call succeeded, for the application's unit/integration testing, WebGPU conformance testing, or detecting errors in a data-driven application (e.g. loading a glTF model that might exceed device limits).
- *Application Telemetry*:
    Collecting error logs in deployment of a web application, for bug reporting and telemetry.

The following sections go into more detail on these cases and how they are handled.

#### Debugging #### {#errors-cases-debugging}

**Solution:** Dev Tools.

Implementations should provide a way to enable synchronous validation,
for example via a "break on WebGPU error" option in the developer tools.

This can be implemented via a content-process&lrarr;gpu-process round-trip in each validated WebGPU call, though in practice this would be very slow.
It can be optimized by running a "predicted" mirror of the validation steps in the content process, which either ignores out-of-memory errors (which it can't predict), or uses round-trips only for the calls that produce
out-of-memory errors.

#### Fatal Errors: Adapter and Device Loss #### {#errors-cases-fatalerrors}

**Solution:** [[#device-loss]].

#### Fallible Allocation, Fallible Validation, and Telemetry #### {#errors-cases-other}

**Solution:** *Error Scopes*.

For important context, see [[#invalid-and-destroyed]]. In particular, all errors (validation and out-of-memory) are detected asynchronously, in a remote process.
In the WebGPU specification, we refer to the worker thread of each WebGPU device as the "device timeline".

As such, applications need a way to instruct the device timeline how to handle any errors that occur. To solve this, WebGPU uses *Error Scopes*.

### Error Scopes ### {#errors-errorscopes}

WebGL exposes errors using the `getError` function which returns the first error since the last `getError` call.
This is simple but has two problems.

- It is synchronous, incurring a round-trip and requiring all previously-issued work to complete.
    We solve this by returning errors asynchronously.
- Its flat state model composes poorly: errors can leak into/out of unrelated code, possibly in libraries/middleware, browser extensions, etc.
    We solve this with a stack of error "scopes", allowing each component to hermetically capture and handle its own errors.

In WebGPU, each device<sup>1</sup> maintains a persistent "error scope" stack state.
Initially, the device's error scope stack is empty.
`GPUDevice.pushErrorScope('validation')` or `GPUDevice.pushErrorScope('out-of-memory')` begins an error scope and pushes it onto the stack.
This scope captures only errors of a particular type depending on the type of error the application wants to detect.
It is rare to need to detect both, so both are rarely needed, requiring two nested error scopes to do so.

`GPUDevice.popErrorScope()` ends an error scope, popping it from the stack and returning a `Promise<GPUError?>`, which resolves once the enclosed operations have completed and reported back.
This includes all fallible operations *issued* between the push and pop calls.
It resolves to `null` if no errors were captured, and otherwise resolves to an object describing the first error captured by the scope - either a `GPUValidationError` or a `GPUOutOfMemoryError`.

Any device timeline error from an operation is passed to the top-most error scope on the stack at the time it was issued.

- If an error scope captures the error, the error is not passed further down the stack. Each error scope only stores the **first** error it captures; any other errors it captures are **silently ignored**.
- If not, the error is passed down the stack to the enclosing error scope.
- If the error reaches the bottom of the stack, it **may**<sup>2</sup> fire an `uncapturederror` event on the `GPUDevice`<sup>3</sup> (and may emit a console warning).

<sup>1</sup>
In the plan to add [[#multithreading]], the error scope state is actually **per-device, per-realm**.
That is, when a GPUDevice is first posted to a Worker, the error scope stack for that device+realm is always empty.
(If a GPUDevice is copied *back* to an execution context where it already exists, it shares its error scope state with all other copies on that execution context.)

<sup>2</sup>
An implementation may choose not to always fire an event for a given error, for example if it has fired too many times, too rapidly, or too many errors of the same kind.
This is similar to how Dev Tools console warnings work in WebGL today.
In a poorly formed application, this mechanism can prevent the event from having a significant performance impact on the system.

<sup>3</sup>
More specifically, with [[#multithreading]], this event will only exist on the *originating* `GPUDevice` (the one from `createDevice`, not one received via a posted message); a distinct interface will be used for non-originating device objects.

```webidl
enum GPUErrorFilter {
    "out-of-memory",
    "validation"
};

interface GPUOutOfMemoryError {
    constructor();
};

interface GPUValidationError {
    constructor(DOMString message);
    readonly attribute DOMString message;
};

typedef (GPUOutOfMemoryError or GPUValidationError) GPUError;

partial interface GPUDevice {
    undefined pushErrorScope(GPUErrorFilter filter);
    Promise<GPUError?> popErrorScope();
};
```

#### How this solves *fallible allocation* #### {#errors-errorscopes-allocation}

If a call that allocates GPU memory (such as `createBuffer` or `createTexture`) fails to allocate, the resulting object is invalid (just as if there were a validation error), but an `'out-of-memory'` error is generated.
It can be detected using an "out-of-memory" error scope.

**Example: tryCreateBuffer**

```ts
async function tryCreateBuffer(device: GPUDevice, descriptor: GPUBufferDescriptor): Promise<GPUBuffer | null> {
  device.pushErrorScope('out-of-memory');
  const buffer = device.createBuffer(descriptor);
  if (await device.popErrorScope() !== null) {
    return null;
  }
  return buffer;
}
```

Since there are many possible out-of-memory situations in an implementation, this interacts with buffer mapping error situations in subtle ways that are not explained here.
The principle used to design the interaction is that application code should have to handle as few distinct edge cases as possible, so multiple situations should lead to the same behavior.

Additionally, there are (will be) rules for the relative ordering of most promise resolutions, to prevent non-portable browser behavior or flaky races between asynchronous code.

#### How this solves *error validation* #### {#errors-errorscopes-validation}

A "validation" error scope can be used to detect validation errors, as described above.

**Example: Testing**

```ts
device.pushErrorScope('out-of-memory');
device.pushErrorScope('validation');

{
  // (Do stuff that shouldn't produce errors.)

  {
    device.pushErrorScope('validation');
    device.doOperationThatIsExpectedToError();
    device.popErrorScope().then(error => { assert(error !== null); });
  }

  // (More stuff that shouldn't produce errors.)
}

// Detect unexpected errors.
device.popErrorScope().then(error => { assert(error === null); });
device.popErrorScope().then(error => { assert(error === null); });
```

#### How this solves *application telemetry* #### {#errors-errorscopes-telemetry}

As described above, if an error scope does not capture an error, it **may** fire the originating device's `uncapturederror` event.
An application can watch for that event, or wrap part of its application in an error scope, to detect errors in order to generate error reports.

`uncapturederror` is not necessary to solve this problem, but it has the benefit of providing a single stream for uncaptured errors across all threads.

#### Error messages and debug labels #### {#errors-errorscopes-labels}

Every WebGPU object has a read-write attribute `label` that an application can set to provide information to debugging tools (error messages, native profilers like Xcode, etc.)
Every WebGPU object creation descriptor has a member `label` used to set the initial value of the attribute.

Additionally, parts of a command buffer can be marked with debug markers and debug groups.
See [[#command-encoding-debug]].

For debugging (developer tools messages) and application telemetry (`uncapturederror`) an implementation may choose to report some kind of "stack trace" in error messages, taking advantage of object debug labels.
For example, a debug message string could be:

```
<myQueue>.submit failed:
- commands[0] (<mainColorPass>) was invalid:
- in the debug group <environment>:
- in the debug group <tree 123>:
- in setIndexBuffer, indexBuffer (<mesh3.indices>) was invalid:
- in createBuffer, desc.usage (0x89) was invalid
```

### Alternatives considered ### {#errors-alternatives}

- Synchronous `getError`, like WebGL. Discussed at the beginning: [[#errors-errorscopes]].
- Callback-based error scopes: `device.errorScope('out-of-memory', async () => { ... })`.
    Since it is necessary to allow asynchronous work within an error scope, this formulation is actually roughly the same as the one shown above, because the callback can never resolve.
    Application architectures would be constrained by the need to conform to a compatible call stack, or they would remap the callback-based API onto a push/pop-based API.
    Finally, if error scopes become unbalanced, it is usually not catastrophic, though the stack could grow without bound, leading to an eventual crash (or device loss).


## Device loss ## {#device-loss}

Anything that prevents further use of a `GPUDevice` results in a *device loss*.
These may be caused by WebGPU calls or by external events; for example:
`device.destroy()`, an unrecoverable out-of-memory situation, a GPU process crash, a long-running operation that causes a GPU reset, a GPU reset caused by another application, turning off a discrete GPU to save power, or an external GPU being unplugged.

**Design principle:**
There should be as few distinct-looking error behaviors as possible.
This makes it easier for developers to test how their application behaves in different situations, improves application robustness, and improves portability between browsers.

Issue: Finish this explainer (see [ErrorHandling.md](https://github.com/gpuweb/gpuweb/blob/main/design/ErrorHandling.md#fatal-errors-requestadapter-requestdevice-and-devicelost)).


## Buffer mapping ## {#buffer-mapping}

A `GPUBuffer` represents a memory allocation that can be used by other GPU operations.
This memory can be accessed linearly, unlike a GPUTexture, for which the actual memory layout of the sequence of texels is unknown. Think of `GPUBuffers` as the result of `gpu_malloc()`.

**CPU&rarr;GPU:** When using WebGPU, applications need to transfer data from JavaScript to a `GPUBuffer` very frequently and potentially in large quantities.
This includes mesh data, drawing and compute parameters, ML model inputs, and so on.
This is why an efficient way to update `GPUBuffer` data is needed. `GPUQueue.writeBuffer` is fairly efficient, but it involves at least one extra copy compared to buffer mapping used to write to the buffer.

**GPU&rarr;CPU:** Applications also frequently need to transfer data from the GPU to JavaScript, though usually less frequently and in smaller quantities.
This includes screenshots, computed statistics, simulation or ML model results, and so on.
This transfer is done through buffer mapping to read from the buffer.

See [[#memory-visibility]] for more background on the various types of memory that buffer mapping interacts with.

### CPU-GPU ownership transfer ### {#buffer-mapping-ownership}

In native GPU APIs, when a buffer is mapped, the CPU can access its content.
At the same time, the GPU can continue to use the buffer's content, which leads to a data race between the CPU and the GPU.
This means that the use of mapped buffers is simple, but leaves synchronization up to the application.

Instead, for portability and consistency, WebGPU prevents almost all data races.
In WebGPU, since some drivers may require an extra "shared memory" step, races on mapped buffers pose an even greater non-portability risk.
This is why `GPUBuffer` mapping is done as an ownership transfer between the CPU and the GPU.
At each instant, only one of the two can access it, so a race is impossible.

When the application requests to map a buffer, it starts the process of transferring ownership of the buffer to the CPU.
At this time, the GPU may still need to finish some operations that use the buffer, so the transfer does not complete until all previously enqueued GPU operations have finished.
This is why mapping a buffer is an asynchronous operation (we will discuss the other parameters below):

<xmp highlight=idl>
typedef [EnforceRange] unsigned long GPUMapModeFlags;
namespace GPUMapMode {
    const GPUFlagsConstant READ  = 0x0001;
    const GPUFlagsConstant WRITE = 0x0002;
};

partial interface GPUBuffer {
  Promise<undefined> mapAsync(GPUMapModeFlags mode,
                              optional GPUSize64 offset = 0,
                              optional GPUSize64 size);
};
</xmp>

<div class=example>
    Using it is done like so:

    <pre highlight="js">
        // Mapping a buffer for writing. Here offset and size are defaulted,
        // so the whole buffer is mapped.
        const myMapWriteBuffer = ...;
        await myMapWriteBuffer.mapAsync(GPUMapMode.WRITE);

        // Mapping a buffer for reading. Only the first four bytes are mapped.
        const myMapReadBuffer = ...;
        await myMapReadBuffer.mapAsync(GPUMapMode.READ, 0, 4);
    </pre>
</div>

Once the application is done using the buffer on the CPU, it can transfer ownership back to the GPU by unmapping it.
This is an immediate operation that makes the buffer inaccessible to the application on the CPU (i.e. detaches the `ArrayBuffers`):

<xmp highlight=idl>
partial interface GPUBuffer {
  undefined unmap();
};
</xmp>

<div class=example>
    Using it is done like so:

    <pre highlight="js">
        const myMapReadBuffer = ...;
        await myMapReadBuffer.mapAsync(GPUMapMode.READ, 0, 4);
        // Do something with the mapped buffer.
        buffer.unmap();
    </pre>
</div>

When transferring ownership to the CPU, a copy from the underlying mapped buffer to shared memory visible to the content process may be needed.
To avoid unnecessary copies, an application can specify the range it is interested in when calling `GPUBuffer.mapAsync`.

The `mode` argument of `GPUBuffer.mapAsync` controls which type of mapping operation is performed.
Currently its value is redundant with the buffer's creation usage flags, but it exists for explicitness and future extensibility.

While a GPUBuffer is owned by the CPU, it is not possible to submit any operations on the device timeline that use it; otherwise, a validation error is produced.
However, it is valid (and encouraged!) to record `GPUCommandBuffer`s using the `GPUBuffer`.

### Creating mappable buffers ### {#buffer-mapping-creation}

The physical memory location of a `GPUBuffer`'s underlying buffer depends on whether it should be mappable and whether it is mappable for reading or writing (for example, native APIs provide some control over CPU caching behavior).
Currently, mappable buffers can only be used to transfer data (so, aside from the `MAP_*` usages, they can only have the corresponding `COPY_SRC` or `COPY_DST` usage),
which is why the application must specify that a buffer is mappable when creating it with the (currently) mutually exclusive `GPUBufferUsage.MAP_READ` and `GPUBufferUsage.MAP_WRITE` flags:

<div class=example>
    <pre highlight="js">
        const myMapReadBuffer = device.createBuffer({
            usage: GPUBufferUsage.MAP_READ | GPUBufferUsage.COPY_DST,
            size: 1000,
        });
        const myMapWriteBuffer = device.createBuffer({
            usage: GPUBufferUsage.MAP_WRITE | GPUBufferUsage.COPY_SRC,
            size: 1000,
        });
    </pre>
</div>

### Accessing mapped buffers ### {#buffer-mapping-access}

Once a `GPUBuffer` is mapped, its memory can be accessed from JavaScript.
This is done by calling `GPUBuffer.getMappedRange`, which returns an `ArrayBuffer` called a "mapping".
These are available until `GPUBuffer.unmap` or `GPUBuffer.destroy` is called, at which point they are detached.
These `ArrayBuffer`s are typically not new allocations, but instead pointers to some kind of shared memory visible to the content process (IPC shared memory, `mmap`ped file descriptor, etc.).

When transferring ownership to the GPU, a copy from shared memory to the underlying mapped buffer may be needed.
`GPUBuffer.getMappedRange` takes an optional range of the buffer to map (where `offset` 0 is the start of the buffer).
This way the browser knows which parts of the underlying `GPUBuffer` have been "invalidated" and need to be updated from the memory mapping.

This range must be within the range requested in `mapAsync()`.

<xmp highlight=idl>
partial interface GPUBuffer {
  ArrayBuffer getMappedRange(optional GPUSize64 offset = 0,
                             optional GPUSize64 size);
};
</xmp>

<div class=example>
    Using it is done like so:

    <pre highlight="js">
        const myMapReadBuffer = ...;
        await myMapReadBuffer.mapAsync(GPUMapMode.READ);
        const data = myMapReadBuffer.getMappedRange();
        // Do something with the data
        myMapReadBuffer.unmap();
    </pre>
</div>

### Mapping buffers at creation ### {#buffer-mapping-at-creation}

A common need is to create a `GPUBuffer` that is already filled with some data.
This could be achieved by creating the final buffer, then a mappable buffer, filling the mappable buffer, and then copying from the mappable buffer to the final buffer, but this would be inefficient.
Instead, this can be done by having the buffer be CPU-owned at creation: we call this "mapped at creation".
All buffers can be mapped at creation, even if they don't have the `MAP_WRITE` buffer usage.
The browser will simply handle transferring the data into the application's buffer.

Once a buffer is mapped at creation, it behaves just like a regularly mapped buffer: `GPUBUffer.getMappedRange()` is used to retrieve `ArrayBuffer`s, and ownership is transferred to the GPU with `GPUBuffer.unmap()`.

<div class=example>
    Mapping at creation is done by passing `mappedAtCreation: true` in the buffer descriptor at creation:

    <pre highlight="js">
        const buffer = device.createBuffer({
            usage: GPUBufferUsage.UNIFORM,
            size: 256,
            mappedAtCreation: true,
        });
        const data = buffer.getMappedRange();
        // write to data
        buffer.unmap();
    </pre>
</div>

When using advanced methods to transfer data to the GPU (using a rolling list of mapped or being-mapped buffers), mapped-at-creation buffers can be used to immediately create additional space to place the data to be transferred.

### Examples ### {#buffer-mapping-examples}

<div class=example>
    The best way to create a buffer with initial data, for example here a [Draco](https://google.github.io/draco/)-compressed 3D mesh:

    <pre highlight="js">
        const dracoDecoder = ...;

        const buffer = device.createBuffer({
            usage: GPUBuffer.VERTEX | GPUBuffer.INDEX,
            size: dracoDecoder.decompressedSize,
            mappedAtCreation: true,
        });

        dracoDecoder.decodeIn(buffer.getMappedRange());
        buffer.unmap();
    </pre>
</div>

<div class=example>
    Retrieving data from a texture rendered on the GPU:

    <pre highlight="js">
        const texture = getTheRenderedTexture();

        const readbackBuffer = device.createBuffer({
            usage: GPUBufferUsage.COPY_DST | GPUBufferUsage.MAP_READ,
            size: 4 * textureWidth * textureHeight,
        });

        // Copy the data from the texture to the buffer.
        const encoder = device.createCommandEncoder();
        encoder.copyTextureToBuffer(
            { texture },
            { buffer, rowPitch: textureWidth * 4 },
            [textureWidth, textureHeight],
        );
        device.submit([encoder.finish()]);

        // Get the data on the CPU.
        await buffer.mapAsync(GPUMapMode.READ);
        saveScreenshot(buffer.getMappedRange());
        buffer.unmap();
    </pre>
</div>

<div class=example>
    Updating a bunch of data on the GPU for one frame:

    <pre highlight="js">
        void frame() {
            // Create a new buffer for our update. In practice, we would reuse buffers by re-mapping them.
            const stagingBuffer = device.createBuffer({
                usage: GPUBufferUsage.MAP_WRITE | GPUBufferUsage.COPY_SRC,
                size: 16 * objectCount,
                mappedAtCreation: true,
            });
            const stagingData = new Float32Array(stagingBuffer.getMappedRange());

            // For each draw, we will:
            // - Put the draw data into stagingData.
            // - Record a copy of stagingData into the uniform buffer used for the draw.
            // - Encode the draw.
            const copyEncoder = device.createCommandEncoder();
            const drawEncoder = device.createCommandEncoder();
            const renderPass = myCreateRenderPass(drawEncoder);
            for (var i = 0; i < objectCount; i++) {
                stagingData[i * 4 + 0] = ...;
                stagingData[i * 4 + 1] = ...;
                stagingData[i * 4 + 2] = ...;
                stagingData[i * 4 + 3] = ...;

                const {uniformBuffer, uniformOffset} = getUniformsForDraw(i);
                copyEncoder.copyBufferToBuffer(
                    stagingBuffer, i * 16,
                    uniformBuffer, uniformOffset,
                    16);

                encodeDraw(renderPass, {uniformBuffer, uniformOffset});
            }
            renderPass.endPass();

            // We are done filling the staging buffer, unmap() so we can submit commands that use it.
            stagingBuffer.unmap();

            // Submit all the copies, then all the draws. The copies will happen before the draws, so that each draw uses the data filled in the for loop above.
            device.queue.submit([
                copyEncoder.finish(),
                drawEncoder.finish()
            ]);
        }
    </pre>
</div>

## Multithreading ## {#multithreading}

Multithreading is a key part of modern graphics APIs.
Unlike OpenGL, newer APIs allow applications to encode commands, submit work, transfer data to the GPU, and so on, from multiple threads simultaneously, thereby relieving CPU bottlenecks.
This is especially relevant to WebGPU, because IDL bindings are typically much slower than C calls.

WebGPU does *not* yet allow multithreaded use of a single `GPUDevice`, but the API has been designed with this in mind from the start.
This section describes its tentative plans for how this would work.

As described in [[#gpu-process]], most WebGPU objects are actually just "handles" that refer to
objects in the browser's GPU process.
As such, allowing these to be shared between threads is relatively straightforward.
For example, a `GPUTexture` object could simply be `postMessage()`'d to another thread, creating a
new `GPUTexture` JavaScript object containing a "handle" to the *same* (refcounted) GPU-process object.

Objects that have client-side state, like `GPUBuffer`.
Applications still need to use them from multiple threads without having to `postMessage` such objects back and forth using `[Transferable]` semantics (which would also create new wrapper objects, invalidating old references).
As such, these objects will also be `[Serializable]`, but with a small amount of (content-side) **shared state**, like a `SharedArrayBuffer`.

Even though access to this shared state is somewhat restricted - it can't be changed arbitrarily fast on a single object - it could still be a timing attack vector, like `SharedArrayBuffer`, so it is tentatively gated behind cross-origin isolation.
See [Timing attacks](https://gpuweb.github.io/gpuweb/#security-timing).

<div class=example>
    Given threads "Main" and "Worker":

    - Main: `const B1 = device.createBuffer(...);`.
    - Main: Send `B1` to Worker using postMessage.
    - Worker: Receive the message &rarr; `B2`.
    - Worker: `const mapPromise = B2.mapAsync()` &rarr; succeeds, putting the buffer into the "map pending" state.
    - Main: `B1.mapAsync()` &rarr; **throws an exception** (and does not change the state of the buffer).
    - Main: Encode some commands using `B1`, e.g.:

        ```js
        encoder.copyBufferToTexture(B1, T);
        const commandBuffer = encoder.finish();
        ```

        &rarr; succeeds, because this does not depend on the client-side state of the buffer.
    - Main: `queue.submit(commandBuffer)` &rarr; **asynchronous WebGPU error**, because the CPU currently owns the buffer.
    - Worker: await mapPromise writes into the mapping, then calls `B2.unmap()`.
    - Main: `queue.submit(commandBuffer)` &rarr; succeeds.
    - Main: `B1.mapAsync()` &rarr; succeeds, putting the buffer into the "map pending" state.
</div>

Further discussion can be found in [#354](https://github.com/gpuweb/gpuweb/issues/354)
(note that not everything reflects current thinking).

### Unresolved: Synchronous Object Transfer ### {#multithreading-transfer}

Some application architectures require objects to be passed between threads without having to asynchronously wait for a message to arrive on the receiving thread.

The most critical class of such architectures is in WebAssembly applications:
programs using native C/C++/Rust/etc. bindings to WebGPU need to assume object handles are plain-old-data that can be passed freely between threads (e.g. `typedef struct WGPUBufferImpl* WGPUBuffer;`).
Unfortunately, this cannot be implemented in C-on-JS bindings (e.g. Emscripten) without complex, hidden, and slow asynchronicity (yielding on the receiving thread, interrupting the sending thread to have it send a message, then waiting for the object on the receiving thread).

Several alternatives are mentioned in issue [#747](https://github.com/gpuweb/gpuweb/issues/747):

- SharedObjectTable, an object with shared state (like SharedArrayBuffer), containing a table of `[Serializable]` values.
    In effect, the storage in the table would be serialized once, and then any thread with the SharedObjectTable could (synchronously) deserialize objects from it on demand.
- A synchronous MessagePort.receiveMessage() method.
    This is less ideal because it requires any thread that creates one of these objects to eagerly send it to every thread, in case they need it later.
- Allow "exporting" a numeric ID for an object that can be used to "import" the object on another thread. This bypasses the garbage collector and can easily leak memory.


## Command Encoding and Submission ## {#command-encoding}

Many operations in WebGPU are purely GPU-side operations that do not use data from the CPU.
These operations are not issued directly; instead, they are encoded into a GPUCommandBuffer via the builder-like GPUCommandEncoder interface, and then sent to the GPU via `gpuQueue.submit()`.
This design is also used by the underlying native APIs. It provides several benefits:

- Command buffer encoding is independent of other state, allowing encoding (and command buffer validation) work to take advantage of multiple CPU threads.
- Providing a larger amount of work at once allows GPU drivers to do more global optimization, particularly in how it schedules work across the GPU hardware.

### Debug markers and debug groups ### {#command-encoding-debug}

For error messages and debugging tools, work can be marked within a command buffer.
(See [[#errors-errorscopes-labels]].)

- `insertDebugMarker(markerLabel)` marks a point in the command stream.
- `pushDebugGroup(groupLabel)`/`popDebugGroup()` demarcate a nested subset of the command stream.
       This can be used to, e.g., mark which part of a command buffer corresponds to different objects or parts of a scene.

### Passes ### {#command-encoding-passes}

Issue: Briefly explain passes?


## Pipelines ## {#pipelines}

## Image, Video, and Canvas input ## {#image-input}

Issue: At the time of this writing, the exact APIs are still in flux.

WebGPU is heavily isolated from the rest of the Web platform, but there are several points of interop.
One of them is image data input into the API.
In addition to the general data read/write mechanisms (writeTexture, writeBuffer, and mapAsync),
data can also come from <img>/ImageBitmap, canvases, and video.
There are many use cases that need these, including:

- Initializing a texture from an encoded image (JPEG, PNG, etc.)
- Rendering text using a 2D canvas for use in WebGPU.
- Video elements and camera input for image processing, ML, 3D scenes, etc.

There are two paths:

- `copyExternalImageToTexture()` copies color data from a sub-rectangle of an image/video/canvas object into an equally-sized sub-rectangle of a GPUTexture.
    The input data is captured at the time of the call.
- `importTexture()` takes a video or canvas and creates a GPUExternalTexture object which, if it already lives on the (same) GPU, *can* provide direct read access to the underlying resource, avoiding unnecessary copies or CPU-GPU bandwidth.
    This generally works for hardware-decoded video and most canvas elements.

Issue: Update the two names to whatever we settle on.

### GPUExternalTexture ### {#image-input-external-texture}

A GPUExternalTexture is a sampleable texture object which can be used in a similar way to a normal sampleable GPUTexture object.
In particular, it can be bound as a texture resource to a shader and used directly from the GPU:
when it is bound, additional metadata allows WebGPU to "automatically" convert the data from its underlying representation (e.g. YUV) to RGB sampled data.

A GPUExternalTexture represents a particular imported image, so the underlying data must not change after import, whether accessed from internally (WebGPU) or externally (the Web platform).

Issue:
Describe how this is achieved for video elements, VideoFrame, canvas elements, and OffscreenCanvas.


## Canvas Output ## {#canvas-output}

Historically, drawing APIs (2d canvas, WebGL) have been initialized from a canvas using `getContext()`.
However, WebGPU is more than just a drawing API, and many applications do not need a canvas.
WebGPU is initialized without a canvas - see [[#initialization]].

Following from this, WebGPU has no "default" drawing buffer.
Instead, a WebGPU device can be connected to *any number* of canvases (zero or more) and render to any number of them each frame.

Canvas context creation and WebGPU device creation are decoupled.
Any GPUCanvasContext can be used dynamically with any GPUDevice.
This makes it easy to switch devices (e.g. after recovering from a device loss).
(In contrast, WebGL context restoration is done on the same WebGLRenderingContext object,
even though context state does not persist across the loss/restore.)

To access a canvas, an application obtains a GPUTexture from a GPUCanvasContext, then writes to it, just like it would with a normal GPUTexture.

### Swap Chains ### {#canvas-output-swap-chains}

Canvas GPUTextures are used in a very structured way:

- `canvas.getContext('gpupresent')` provides a 'GPUCanvasContext'.
- `GPUCanvasContext.configureSwapChain({ device, format, usage })` provides a 'GPUSwapChain',
    invalidating any previous swap chain, attaching the canvas to the provided device, and setting the 'GPUTextureFormat' and 'GPUTextureUsage' for the textures used.
- `GPUSwapChain.getCurrentTexture()` provides a 'GPUTexture'.

This structure provides maximum compatibility with optimized paths in native graphics APIs.
In these, typically, a platform-specific "surface" object can produce an API object known as a "swap chain" which may provide, possibly up front, a possibly-fixed list of 1-3 textures to render into.

### Current Texture ### {#canvas-output-current-texture}

A 'GPUSwapChain' provides a "current texture" via 'getCurrentTexture()'.
For a <{canvas}> element, this returns a texture for the *current frame*:

- On `getCurrentTexture()`, the 'currentTexture' is created if it doesn't exist, then returned.
- During the "[=Update the rendering=]" step, the browser compositor takes ownership of the 'currentTexture' for display, and that internal slot is cleared for use by the next frame.

### `getSwapChainPreferredFormat()` ### {#canvas-output-preferred-format}

Due to differences in framebuffer hardware, different devices have different preferred byte layouts for display surfaces.
All systems allow the use of any of the allowed formats, but applications can save power by using the preferred format.
The exact format cannot be hidden, because the format is observable - for example, in the behavior of 'copyBufferToTexture' calls and in the compatibility rules with render pipelines (which specify a format, see `GPUColorTargetState.format`).

Desktop-lineage hardware generally prefers 'bgra8unorm' (4 bytes in BGRA order), while mobile-lineage hardware generally prefers 'rgba8unorm' (4 bytes in RGBA order).

For high bit depth, different systems may also prefer different formats, like 'rgba16float' or 'rgb10a2unorm'.

### Multiple Displays ### {#canvas-output-multiple-displays}

Some systems have multiple displays with different capabilities (e.g. HDR vs non-HDR).
A browser window can be moved between these displays.

As with WebGL today, a user agent can decide for itself how to expose these capabilities, e.g. choosing the capabilities of the initial, primary, or most capable display.

In the future, an event may be provided that allows applications to detect when a canvas moves to a display with different properties, so that they can call getSwapChainPreferredFormat() and configureSwapChain() again.

#### Multiple Adapters #### {#canvas-output-multiple-adapters}

Some systems have multiple displays connected to different hardware adapters; for example, a laptop with switchable graphics might connect the internal display to the integrated GPU and the HDMI port to the discrete GPU.

This can incur overhead, because rendering on one adapter and displaying on another typically results in a copy or direct memory access (DMA) over the PCI bus.

Currently, WebGPU provides no way to detect which adapter is best for a given display.
In the future, applications may be able to detect this, and receive an event when it changes.


## Bitflags ## {#bitflags}

WebGPU uses C-style bitflags in several places.
(Search for GPUFlagsConstant in the specification for instances.)
A typical bitflags definition looks like this:

<xmp highlight=idl>
typedef [EnforceRange] unsigned long GPUColorWriteFlags;
[Exposed=Window]
namespace GPUColorWrite {
    const GPUFlagsConstant RED   = 0x1;
    const GPUFlagsConstant GREEN = 0x2;
    const GPUFlagsConstant BLUE  = 0x4;
    const GPUFlagsConstant ALPHA = 0x8;
    const GPUFlagsConstant ALL   = 0xF;
};
</xmp>

This was chosen because there is no other particularly ergonomic way to describe "enum sets" in JavaScript today.

Bitflags are used in WebGL, and will be familiar to many WebGPU developers.
They also match closely with the API shapes that many native language bindings will use.

The closest option would be sequence<enum type>, but it would not naturally describe an unordered set of unique items, and would not easily allow something like GPUColorWrite.ALL above.
Additionally, sequence<enum type> has significant overhead, so we would have to avoid it in any API expected to be a "hot path" (like command encoder methods), resulting in an inconsistency with the parts of the API that *do* use it.

Please see issue [#747](https://github.com/gpuweb/gpuweb/issues/747)
which mentions that strongly-typed bitflags in JavaScript would be useful.


# Security and Privacy (self-review) # {#questionnaire}

This section is a security and privacy self-review.
You may also want to look at the specification's [Malicious use considerations](https://gpuweb.github.io/gpuweb/#malicious-use) section.

## What information might this feature expose to Web sites or other parties, and for what purposes is that exposure necessary? ## {#questionnaire-1}

The feature exposes information about the system's GPU (or lack thereof).

It allows determining whether one of the system's GPUs supports WebGPU, by requesting a GPUAdapter without a software fallback.
This is necessary for a site to be able to fall back to hardware-accelerated WebGL if the system does not support hardware-accelerated WebGPU.

For a requested adapter, the feature exposes a name, a set of optional WebGPU features that the GPUAdapter supports, and a set of numeric limits that the GPUAdapter supports.
This is necessary because there is a lot of diversity in GPU hardware, and while WebGPU targets the lowest common denominator, it is meant to be extensible where hardware allows to expose more powerful features.
The name can be displayed to the user at selection time, for example to let it choose an adapter, and the name can be used by sites to perform GPU-specific workarounds (this was critical for WebGL in the past).

Note that the user agent controls which name, optional features, and limits are exposed.
It is not possible for a site to distinguish hardware that does not support a feature from a user agent that chose not to expose it.
The user agent should bucket the actual capabilities of the GPU, and only expose a limited number of such buckets to sites.

## Is this specification exposing the minimum amount of information necessary to power its features? ## {#questionnaire-2}

Yes.
WebGPU only needs to expose whether hardware-accelerated WebGPU is available, not why, or whether the browser chose not to expose it, etc.

For the name, optional features, and limits, the information exposed is not specified to be minimal, because each site may need a different subset of the limits and optional features.
Instead, the information exposed is controlled by the user agent, which is expected to only expose a small number of buckets that all expose the same information.

## How does this specification deal with personal information, personally-identifiable information (PII), or information derived from them? ## {#questionnaire-3}

WebGPU does not deal with PII, unless a site puts PII into the API, which means the Javascript had access to the PII before WebGPU.

## How does this specification deal with sensitive information? ## {#questionnaire-4}

WebGPU does not deal with sensitive information.
However, some of the information it exposes could be correlated with sensitive information: the presence of powerful optional features or high-speed GPU compute would allow inferring access to a "high-end" GPU, which is itself correlated with other information.

## Does this specification introduce new state for an origin that persists across browsing sessions? ## {#questionnaire-5}

The WebGPU specification does not introduce new state.
However, implementations are expected to cache the result of compiling shaders and pipelines.
This introduces state that can be probed by measuring the time it takes to compile a set of shaders and pipelines.
Note that GPU drivers also have their own caches, so the user agent must find a way to disable that cache (otherwise the state could leak across origins).

## Does this specification expose information about the underlying platform to origins? ## {#questionnaire-6}

Yes.
The specification exposes whether hardware-accelerated WebGPU is available, and a user-agent-controlled name and set of optional features and limits that each GPUAdapter supports.
Different requests returning adapters with different capabilities also indicates that the system contains multiple GPUs.

## Does this specification allow an origin to send data to the underlying platform? ## {#questionnaire-7}

WebGPU allows sending data to the system's GPU.
The WebGPU specification prevents sending malformed GPU commands to the hardware.
User agents are also expected to provide workarounds for bugs in drivers, where even well-formed GPU commands could cause issues.

## Does this specification allow an origin access to sensors on a user's device? ## {#questionnaire-8}

No.

## What data does this specification expose to an origin? Please also document what data is identical to data exposed by other features, in the same or different contexts. ## {#questionnaire-9}

WebGPU exposes whether hardware-accelerated WebGPU is available, which is a new piece of data.
The name, optional features, and limits of the adapter intersect heavily with WebGL's RENDERER_STRING, limits, and extensions: even limits that are not in WebGL can be derived from other limits exposed by WebGL (by inferring the model of GPU the system has).

## Does this specification enable new script execution/loading mechanisms? ## {#questionnaire-10}

Yes.
WebGPU allows running arbitrary GPU computations specified by the WebGPU Shading Language (WGSL).
WGSL is compiled into a GPUShaderModule object, which is then used to specify "pipelines" that run computations on the GPU.

## Does this specification allow an origin to access other devices? ## {#questionnaire-11}

No.
WebGPU allows accessing PCI-e and external GPUs plugged into the system, but these are just part of the system.

## Does this specification allow an origin some measure of control over a user agent's native UI? ## {#questionnaire-12}

No.
However, WebGPU can be used to render to fullscreen or WebXR, which changes the UI.
WebGPU can also run GPU computations that take too long, and cause the device to time out and the GPU to restart (TDR), which produces several system-wide black frames.
Note that this is achievable with "just" HTML/CSS, but WebGPU can cause TDRs more easily.

## What temporary identifiers might this specification create or expose to the web? ## {#questionnaire-13}

None.

## How does this specification distinguish between behavior in first-party and third-party contexts? ## {#questionnaire-14}

There is no specific behavior difference between first-party and third-party contexts.
However, a user agent may decide to restrict the GPUAdapters returned to third-party contexts: by using fewer buckets, using a single bucket, or not exposing WebGPU at all.

## How does this specification work in the context of a user agent's Private Browsing or Incognito mode? ## {#questionnaire-15}

There is no difference in Incognito mode, but a user agent may decide to restrict the GPUAdapters returned.
User agents need to be careful not to reuse the shader compilation cache in Incognito mode.

## Does this specification have both "Security Considerations" and "Privacy Considerations" sections? ## {#questionnaire-16}

Yes.
They are both under the [Malicious use considerations](https://gpuweb.github.io/gpuweb/#malicious-use) section.

## Does this specification allow downgrading default security characteristics? ## {#questionnaire-17}

No.
Except that WebGPU can be used to render to fullscreen or WebXR.

## What should this questionnaire have asked? ## {#questionnaire-18}

Does the specification allow interacting with cross-origin data? Using DRM data?

Currently WebGPU cannot do this, but it is likely that in the future someone will ask for these features.
It is possible to introduce the concept of a "protected queue", which only allows computations to end up on the screen, and not in Javascript.
However, investigations in WebGL have shown that GPU timing can be used to leak from such protected queues.

# WebGPU Shading Language # {#wgsl}


